[buildOptions]
    optimizeWithTtx = true

[buildPlans.Iosevkaneg]
    family = 'Iosevka'
    desc = 'Default'
    calt = false
    exportGlyphNames = true
    spacing = 'fontconfig-mono'
    snapshotFamily = 'iosevka'
    snapshotFeature = '"NWID" off'

[buildPlans.Iosevkaneg.ligations]
    inherits = 'default-calt'
    brace-bar = false
    brack-bar = false
    connected-tilde-as-wave = false
    connected-hyphen-as-solid-line = false
    connected-hyphen-as-semi-dashed-line = false

[buildPlans.Iosevkaneg.variants.design]
    capital-a = 'straight-top-serifed'
    capital-b = 'standard-unilateral-serifed'
    capital-c = 'unilateral-inward-serifed'
    capital-d = 'standard-bilateral-serifed'
    capital-e = 'serifed'
    capital-f = 'serifed'
    capital-g = 'toothed-serifed-hooked'
    capital-h = 'top-left-serifed'
    capital-i = 'short-serifed'
    capital-j = 'serifed-both-sides'
    capital-k = 'straight-bottom-right-serifed'
    capital-l = 'motion-serifed'
    capital-m = 'hanging-motion-serifed'
    capital-n = 'standard-motion-serifed'
    capital-p = 'closed-motion-serifed'
    capital-q = 'crossing-curly-tailed'
    capital-r = 'straight-open-serifed'
    capital-s = 'unilateral-inward-serifed'
    capital-t = 'serifless'
    capital-u = 'toothed-serifless'
    capital-v = 'straight-motion-serifed'
    capital-w = 'straight-motion-serifed'
    capital-x = 'straight-unilateral-motion-serifed'
    capital-y = 'curly-serifless'
    capital-z = 'curly-serifed'
    capital-delta = 'curly'
    a = 'double-storey-tailed'
    b = 'toothed-serifless'
    c = 'serifless'
    d = 'toothed-serifed'
    e = 'flat-crossbar'
    f = 'flat-hook-tailed'
    g = 'double-storey'
    h = 'tailed-serifed'
    i = 'serifed-flat-tailed'
    j = 'serifed'
    k = 'symmetric-touching-top-left-serifed'
    l = 'serifed-semi-tailed'
    m = 'tailed-top-left-serifed'
    n = 'straight-serifless'
    p = 'eared-serifless'
    q = 'straight-serifless'
    r = 'corner-hooked-serifless'
    s = 'bilateral-inward-serifed'
    t = 'bent-hook'
    u = 'toothed-serifless'
    v = 'curly-motion-serifed'
    w = 'straight-motion-serifed'
    x = 'curly-unilateral-motion-serifed'
    y = 'curly-turn-motion-serifed'
    z = 'curly-serifed'
    lower-alpha = 'crossing'
    capital-gamma = 'serifed'
    lower-delta = 'rounded'
    lower-lambda = 'curly-turn'
    lower-mu = 'tailed-serifless'
    lower-xi = 'flat-top'
    cyrl-capital-ze = 'bilateral-inward-serifed'
    cyrl-ze = 'serifless'
    cyrl-capital-ka = 'curly-serifless'
    cyrl-ka = 'curly-serifless'
    cyrl-el = 'straight'
    cyrl-ef = 'top-serifed'
    cyrl-che = 'standard'
    cyrl-capital-ya = 'curly-serifless'
    cyrl-ya = 'curly-serifless'
    zero = 'slashed'
    one = 'base-long-top-serif'
    two = 'curly-neck-serifed'
    three = 'flat-top-serifed'
    four = 'semi-open-serifed'
    five = 'oblique-arched-serifed'
    six = 'closed-contour'
    seven = 'curly-serifed'
    eight = 'crossing'
    nine = 'open-contour'
    punctuation-dot = 'round'
    tilde = 'low'
    asterisk = 'turn-hex-low'
    underscore = 'low'
    caret = 'low'
    ascii-grave = 'straight'
    ascii-single-quote = 'straight'
    paren = 'flat-arc'
    brace = 'straight'
    number-sign = 'upright'
    ampersand = 'closed'
    at = 'fourfold'
    dollar = 'interrupted'
    cent = 'bar-interrupted'
    percent = 'rings-segmented-slash'
    bar = 'force-upright'
    question = 'corner'
    lig-ltgteq = 'slanted'

[buildPlans.Iosevkaneg.weights.Regular]
    shape = 400
    menu = 400
    css = 400

[buildPlans.Iosevkaneg.weights.Medium]
    shape = 500
    menu = 500
    css = 500

[buildPlans.Iosevkaneg.weights.Bold]
    shape = 700
    menu = 700
    css = 700

[buildPlans.Iosevkaneg.slopes.Upright]
    angle = 0
    shape = "upright"
    menu = "upright"
    css = "normal"

[buildPlans.Iosevkaneg.slopes.Italic]
    angle = 9.4
    shape = "italic"
    menu = "italic"
    css = "italic"

[collectPlans.Iosevkaneg]
    release = true
    from = ['Iosevkaneg',]

[widths.normal]
    shape = 5
    menu  = 5
    css   = 'normal'
