http:
  pprof:
    port: 6060
    enabled: false
  address: 127.0.0.1:3000
  session_ttl: 720h
dns:
  bind_hosts:
    - 127.0.0.1
  port: 53
  upstream_dns:
    - 127.0.0.1:5353
  bootstrap_dns:
    - 1.1.1.1
    - 8.8.8.8
  enable_dnssec: false
  cache_size: 4194304
  cache_ttl_min: 0
  cache_ttl_max: 0
  cache_optimistic: true
  upstream_mode: parallel
filtering:
  protection_enabled: true
  filtering_enabled: true
  parental_enabled: false
  safebrowsing_enabled: false
  safe_search:
    enabled: false
filters:
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt
    name: AdGuard DNS filter
    id: 1
  - enabled: true
    url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_2.txt
    name: AdAway Default Blocklist
    id: 2
user_rules: []
schema_version: 29
