[mgr]
prepend_keymap = [
  { on = ["g", "s"], run = "plugin save-file --args=overwrite", desc = "Save (Default/Overwrite)" },
  { on = ["g", "z"], run = "plugin save-file --args=input", desc = "Save as new file (Input)" },
  { on = ["<C-s>"], run = "quit", desc = "Confirm selection (Save)" },
  { on = ["g", "r"], run = '''shell -- ya emit cd "$(git rev-parse --show-toplevel)"''', desc = "Go to git root" },
  { on = ["<Esc>"], run = "close" },
  { on = ["<C-q>"], run = "close" },
  { on = ["d"], run = "yank --cut" },
  { on = ["D"], run = "remove --force" },
  { on = ["X"], run = "remove --permanently" },
  { on = ["f"], run = '''shell "$SHELL" --block''', desc = "Open $SHELL here" },
  { on = ["p"], run = "plugin smart-paste", desc = "Smart paste" },
  { on = ["g", "p"], run = "plugin paste-to-select", desc = "Reveal file from clipboard" },
]
