# Wiremix Configuration
# Documentation: https://github.com/tsowell/wiremix/blob/master/wiremix.toml

# Visuals
theme = "nocolor"
char_set = "compat"

# Naming: Clean up long device names where possible
[names]
stream = [ "{node:node.name}: {node:media.name}" ]

# Keybindings: F-Keys for Tab Switching
keybindings = [
 { key = { F = 1 }, action = { SelectTab = 0 } }, # Playback
 { key = { F = 2 }, action = { SelectTab = 1 } }, # Recording
 { key = { F = 3 }, action = { SelectTab = 2 } }, # Output Devices
 { key = { F = 4 }, action = { SelectTab = 3 } }, # Input Devices
 { key = { F = 5 }, action = { SelectTab = 4 } }, # Configuration
]
